// this is actionTypes
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENTWITHFIVE = 'INCREMENTWITHFIVE';
export const DECREMENTWITHFIVE = 'DECREMENTWITHFIVE';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';